org.gradle.caching=true
org.gradle.configuration-cache=false
org.gradle.daemon=true
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true
loom.ignoreDependencyLoomVersionValidation=true

project.libs=26.1-SNAPSHOT
project.platforms=Common, Fabric, NeoForge
project.plugins=1.1-SNAPSHOT

mod.authors=Fuzs
mod.description=Animals no longer stay in the world forever, instead they spawn and disappear like monsters.
mod.group=fuzs.respawninganimals
mod.id=respawninganimals
mod.license=MPL-2.0
mod.name=Respawning Animals
mod.version=26.1.0

dependencies.fabric.fabricapi=required
dependencies.fabric.forgeconfigapiport=required
dependencies.fabric.puzzleslib=required
dependencies.neoforge.puzzleslib=required

distributions.curseforge.id=322765
distributions.curseforge.slug=respawning-animals
distributions.github.slug=respawning-animals
distributions.modrinth.id=WnwcSeWc
distributions.modrinth.slug=respawning-animals

environments.client=optional
environments.server=required
